import = [ "~/.config/alacritty/themes/themes/catppuccin.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "HackNerdFont"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true

[shell]
program = "tmux"
args = ["new-session", "-A", "-s", "general"]
