import = [ "~/.config/alacritty/themes/themes/catppuccin.toml" ]

[bell]
duration = 0

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "HackNerdFont"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = true
