import = [ "~/.config/alacritty/themes/themes/catppuccin.toml" ]

[bell]
duration = 0

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "Inconsolata Nerd Font"
style = "Regular"

# [[keyboard.bindings]]
# chars = "#"
# key = "Key3"
# mods = "Alt"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = true
