tap "heroku/brew"

brew 'cmake'
brew 'ctags'
brew 'curl'
brew 'git'
brew 'git-extras'
brew 'gnu-tar'
brew 'heroku/brew/heroku'
brew 'htop-osx'
brew 'hub'
brew 'libxml2'
brew 'neovim', args: ['HEAD']
brew 'node'
brew 'openssl'
brew 'optipng'
brew 'rbenv', args: ['HEAD']
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ruby-build'
brew 'tmux'
brew 'wget'
brew 'youtube-dl'
brew 'z'
brew 'zsh-completions'
