#!/usr/bin/env bash

# Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Dotfiles
mkdir -p code
cd code
if [ ! -d 'dotfiles' ]; then
  git clone https://github.com/thejspr/dotfiles.git
fi
cd dotfiles
git pull origin master
rake links

#Prezto
cd ~
zsh
git clone --recursive https://github.com/thejspr/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
chsh -s /usr/local/bin/zsh
echo 'source "${ZDOTDIR:-$HOME}/code/dotfiles/zsh_mods"' >> ~/.zshrc

# Install brew bundles
cd ~/code/dotfiles
brew bundle

# Ruby
rbenv install 2.6.3
gem update --system

# Launch vim to install plugins
# 1. https://neovim.io/doc/user/nvim.html#nvim-from-vim
mkdir -p ~/.vim
vim -c PlugInstall
