#!/usr/bin/env bash

# Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Dotfiles
mkdir -p code
cd code
if [ ! -d 'dotfiles' ]; then
  git clone https://github.com/thejspr/dotfiles.git
fi
cd dotfiles
git pull origin master
rake links

# oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
echo 'source "~/code/dotfiles/zsh_mods"' >> ~/.zshrc

# Install brew bundles
cd ~/code/dotfiles
brew bundle

# Ruby
rbenv install 2.6.3
gem update --system

# Launch vim to install plugins
# 1. https://neovim.io/doc/user/nvim.html#nvim-from-vim
mkdir -p ~/.vim
vim -c PlugInstall
