#!/bin/bash

# Install extra dev things for arch
sudo pacman -Syu --noconfirm
sudo yay -S --noconfirm \
  spotify \
  pipewire \
  pipewire-pulse \
  pipewire-jack \
  wireplumber \
  tmux \
  github-cli \
  mise \
  zsh-syntax-highlighting \
  zsh-autosuggestions \
  zoxide \
  atuin

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# mv ~/.config/nvim ~/.config/nvim-bak
# ln -s ~/.dotfiles/nvim ~/.config/nvim

git clone git@github.com:dokku/dokku.git ~/.dokku

touch ~/.darkmode
touch ~/.secrets

gh auth login

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

mkdir -p ~/code
gh repo clone thejspr/budgie ~/code/budgie
gh repo clone thejspr/measurehub ~/code/measurehub
gh repo clone thejspr/meet_the_danes ~/code/meet_the_danes

mise install ruby
mise install nodejs
