#!/bin/bash

# Install extra dev things for arch
sudo pacman -Syu --noconfirm
sudo yay -S --noconfirm \
  spotify \
  # pipewire \
  # pipewire-pulse \
  # pipewire-jack \
  # wireplumber \
  tmux \
  slack-desktop \
  github-cli \
  mise \
  zsh-syntax-highlighting \
  zsh-autosuggestions \
  zoxide \
  atuin

if [ ! -d ~/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

# mv ~/.config/nvim ~/.config/nvim-bak
# ln -s ~/.dotfiles/nvim ~/.config/nvim

if [ ! -d ~/.dokku ]; then
  git clone git@github.com:dokku/dokku.git ~/.dokku
fi

touch ~/.darkmode
touch ~/.secrets

gh auth login

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# if code directory doesn't exist, create it
if [ ! -d ~/code ]; then
  mkdir ~/code
  gh repo clone thejspr/budgie ~/code/budgie
  gh repo clone thejspr/measurehub ~/code/measurehub
  gh repo clone thejspr/meet_the_danes ~/code/meet_the_danes
fi

mise install ruby
mise install nodejs

npm install -g @anthropic-ai/claude-code
