#!/usr/bin/env ruby

FILES = %w[bin zshrc default-gems default-npm-packages gemrc gitconfig gitattributes gitignore pryrc psqlrc railsrc rgignore ripgreprc tmux.conf tool-versions].freeze

FILES.each do |file|
  target = if file == 'bin'
             "~/#{file}"
           else
             "~/.#{file}"
           end

  file_target = File.expand_path(target)

  if File.symlink?(file_target)
    puts "#{file} symlink, skipping" if ARGV.include?('-v')
    next
  elsif File.exist?(file_target)
    puts "#{file} exists in root. [d]elete? [c]opy? [i]gnore?"
    prompt = $stdin.gets.chomp

    case prompt
    when 'd'
      system "rm -f #{file_target}"
    when 'c'
      puts "Copying and removing #{file_target}"
      system "cp #{file_target} ."
      system "rm -f #{file_target}"
    else
      puts 'Ignoring...'
      next
    end
  end

  cmd = "ln -sf #{File.expand_path(file)} #{file_target}"
  puts cmd
  system(cmd)
end

puts 'Finished updating symlinks'
