#!/usr/bin/env ruby

FILES = {
  'aliases' => '.aliases',
  'bin' => 'bin',
  'zshrc' => '.zshrc',
  'default-gems' => '.default-gems',
  'default-npm-packages' => '.default-npm-packages',
  'gemrc' => '.gemrc',
  'gitconfig' => '.gitconfig',
  'gitattributes' => '.gitattributes',
  'gitignore' => '.gitignore',
  'pryrc' => '.pryrc',
  'psqlrc' => '.psqlrc',
  'railsrc' => '.railsrc',
  'rgignore' => '.rgignore',
  'ripgreprc' => '.ripgreprc',
  'tmux.conf' => '.tmux.conf',
  'vimrc' => '.vimrc',
  'niri' => '.config/niri',
  'nvim' => '.config/nvim',
  'waybar' => '.config/waybar',
  'alacritty.toml' => '.config/alacritty/alacritty.toml',
}.freeze

FILES.each do |file, target|
  file_target = File.expand_path("~/#{target}")

  if File.symlink?(file_target)
    puts "#{file} symlink, skipping" if ARGV.include?('-v')
    next
  elsif File.exist?(file_target)
    puts "#{file} exists in root. [d]elete? [c]opy? [i]gnore?"
    prompt = $stdin.gets.chomp

    case prompt
    when 'd'
      system "cp -r #{file_target} #{file_target}.bak"
      system "rm -fr #{file_target}"
    when 'c'
      puts "Copying and removing #{file_target}"
      system "cp #{file_target} ."
      system "rm -fr #{file_target}"
    else
      puts 'Ignoring...'
      next
    end
  end

  cmd = "ln -sf #{File.expand_path(file)} #{file_target}"
  puts cmd
  system(cmd)
end

puts 'Finished updating symlinks'
