#!/usr/bin/env ruby

IGNORES = %w[zsh_mods ctags tags README.md update-symlinks scripts template.rb].freeze

Dir.glob('*').each do |file|
  next if IGNORES.include?(file)
  next if file =~ /.bak$/

  target = if file == 'bin'
             "~/#{file}"
           else
             "~/.#{file}"
           end

  file_target = File.expand_path(target)

  if File.symlink?(file_target)
    puts "#{file} symlink, skipping" if ARGV.include?('-v')
    next
  elsif File.exist?(file_target)
    puts "#{file} exists in root. [d]elete? [c]opy? [i]gnore?"
    prompt = $stdin.gets.chomp

    case prompt
    when 'd'
      system "rm -f #{file_target}"
    when 'c'
      puts "Copying and removing #{file_target}"
      system "cp #{file_target} ."
      system "rm -f #{file_target}"
    else
      puts 'Ignoring...'
      next
    end
  end

  cmd = "ln -sf #{File.expand_path(file)} #{file_target}"
  puts cmd
  system(cmd)
end

puts 'Finished updating symlinks'
