#!/usr/bin/env ruby

def time
  Time.now.hour
end

def value
  if time > 19
    0.6
  elsif time > 18
    0.7
  elsif time > 17
    0.8
  elsif time > 16
    0.9
  else
    1
  end
end

def set_brightness
  system "xrandr --output HDMI-0 --brightness #{value}"
  system("setbg #{time > 18 ? 'dark' : 'light'}")
end

loop do
  set_brightness
  sleep(60)
end
