#!/usr/bin/env ruby

# frozen_string_literal: true

def time
  Time.now.hour
end

def value
  if time > 15
    0.6
  else
    1
  end
end

def set_brightness
  system "xrandr --output HDMI-0 --brightness #{value}"
  system "xrandr --output DP-4 --brightness #{value}"
  # system("setbg #{time > 18 ? 'dark' : 'light'}")
end

loop do
  set_brightness
  sleep(3600)
end
