#!/usr/bin/env ruby

# Present now playing info

def playerctl_section(section)
  `playerctl metadata #{section}`.delete("\n").strip
end

# Return nothing if not playing
return unless `playerctl -p spotify status`.delete("\n") == 'Playing'

artist = playerctl_section('artist')
track = playerctl_section('title')
album = playerctl_section('album')
artist = album if artist.empty? && !track.include?(album)

return if artist == 'No players found'

puts [artist, track].reject(&:empty?).join(' - ')
