#!/usr/bin/env ruby

volume = `amixer -D pulse get Master | awk -F 'Left:|[][]' 'BEGIN {RS=""}{ print $3 }'`

muted = `amixer -D pulse get Master`.include?('off')

if muted
  puts '🔇'
else
  puts volume
end
